// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxVeQMF-HOP2FwSqXtPiQe-2l_wnnZQ5Q',
    appId: '1:1018791393605:android:c18d62968a6aedd46ba62c',
    messagingSenderId: '1018791393605',
    projectId: 'cablow-driver',
    storageBucket: 'cablow-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28Y243bcacZ14WAvcDx5K0IMyFUPmCmI',
    appId: '1:1018791393605:ios:cfb9aebda6ff99266ba62c',
    messagingSenderId: '1018791393605',
    projectId: 'cablow-driver',
    storageBucket: 'cablow-driver.appspot.com',
    iosBundleId: 'com.example.cablowdriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQwWB3FMDeN6rC8Q7gqx3c7ki5cjo9DYQ',
    appId: '1:1018791393605:web:fbc710f35a2c7d1c6ba62c',
    messagingSenderId: '1018791393605',
    projectId: 'cablow-driver',
    authDomain: 'cablow-driver.firebaseapp.com',
    storageBucket: 'cablow-driver.appspot.com',
    measurementId: 'G-1KCQDJZBE2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28Y243bcacZ14WAvcDx5K0IMyFUPmCmI',
    appId: '1:1018791393605:ios:cfb9aebda6ff99266ba62c',
    messagingSenderId: '1018791393605',
    projectId: 'cablow-driver',
    storageBucket: 'cablow-driver.appspot.com',
    iosBundleId: 'com.example.cablowdriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQwWB3FMDeN6rC8Q7gqx3c7ki5cjo9DYQ',
    appId: '1:1018791393605:web:b4c015efc66dc6d76ba62c',
    messagingSenderId: '1018791393605',
    projectId: 'cablow-driver',
    authDomain: 'cablow-driver.firebaseapp.com',
    storageBucket: 'cablow-driver.appspot.com',
    measurementId: 'G-51RPB8KJ25',
  );

}