name: cablow_user
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.6
  intl_phone_number_input: ^0.7.4
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  device_info_plus: ^10.1.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  rxdart: ^0.28.0
  firebase_analytics: ^11.2.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  location: ^7.0.0
  flutter_typeahead: ^5.2.0
  dio: ^5.6.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2

  # google_places_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: ^0.13.1
flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # Example for adding custom fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Cablow.png"
